run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic

linters-settings:
  govet:
    enable-all: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
