// Package javascript implements the Language interface for JavaScript, TypeScript,
// JSX, and TSX files. Uses a token-based approach: a lexer tokenizes source, a
// normalizer applies the same levels as Go (raw/light/strong/semantic), and an
// extractor identifies function boundaries and statement windows.
//
// No external parser deps — no tree-sitter, no CGO. The tokenizer handles all
// JS/TS syntax including template literals, arrow functions, async/await,
// optional chaining, and TypeScript type annotations.
package javascript

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"go/token"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/user/amimica/internal/config"
	"github.com/user/amimica/internal/lang"
	"github.com/user/amimica/internal/model"
)

// Lang implements lang.Language for JavaScript/TypeScript.
type Lang struct{}

func New() *Lang { return &Lang{} }

func (l *Lang) Name() string { return "javascript" }

func (l *Lang) Extensions() []string {
	return []string{".js", ".jsx", ".ts", ".tsx", ".mjs", ".mts"}
}

func (l *Lang) IsTestFile(path string) bool {
	base := filepath.Base(path)
	return strings.Contains(base, ".test.") ||
		strings.Contains(base, ".spec.") ||
		strings.Contains(base, "_test.") ||
		strings.HasPrefix(base, "test_") ||
		strings.Contains(path, "/__tests__/") ||
		strings.Contains(path, "/test/") ||
		strings.Contains(path, "/tests/")
}

func (l *Lang) IsGeneratedFile(content []byte) bool {
	check := content
	if len(check) > 2048 {
		check = check[:2048]
	}
	s := string(check)
	return strings.Contains(s, "DO NOT EDIT") ||
		strings.Contains(s, "auto-generated") ||
		strings.Contains(s, "Auto-generated") ||
		strings.Contains(s, "Generated by") ||
		strings.Contains(s, "@generated")
}

func (l *Lang) ParseAndExtract(sf model.SourceFile, cfg *config.Config, level model.NormalizationLevel, log *slog.Logger) ([]model.NormalizedUnit, error) {
	content, err := os.ReadFile(sf.Path)
	if err != nil {
		return nil, err
	}
	rawTokens := tokenize(content)
	if len(rawTokens) == 0 {
		return nil, nil
	}
	funcs := findFunctions(rawTokens, content)
	var units []model.NormalizedUnit

	for _, fn := range funcs {
		// Check for amimica-ignore directive.
		if lang.HasIgnoreComment(content, fn.startLine) {
			continue
		}

		normBody := normalizeTokens(fn.bodyTokens, level)
		stmtCount := estimateStatements(normBody)
		if stmtCount < cfg.Analysis.MinStatements {
			continue
		}
		lines := fn.endLine - fn.startLine + 1
		if lines < cfg.Analysis.MinLines {
			continue
		}

		region := model.SourceRegion{
			File:      sf.RelPath,
			StartLine: fn.startLine,
			EndLine:   fn.endLine,
			FuncName:  fn.name,
		}
		units = append(units, makeUnit(normBody, region, model.UnitFunction, level, stmtCount))

		// Statement windows.
		if stmtCount >= cfg.Analysis.WindowMinFunctionSize {
			stmts := splitStatements(normBody)
			winSize := cfg.Analysis.WindowSize
			for i := 0; i <= len(stmts)-winSize; i++ {
				var winTokens []model.NormToken
				for _, s := range stmts[i : i+winSize] {
					winTokens = append(winTokens, s...)
				}
				if len(winTokens) < 5 {
					continue
				}
				wr := model.SourceRegion{
					File:      sf.RelPath,
					StartLine: fn.startLine + i,
					EndLine:   fn.startLine + i + winSize,
					FuncName:  fn.name,
				}
				units = append(units, makeUnit(winTokens, wr, model.UnitWindow, level, winSize))
			}
		}
	}
	return units, nil
}

// --- Tokenizer ---

type jsToken struct {
	typ  int
	val  string
	line int
}

const (
	jtIdent    = 0
	jtKeyword  = 1
	jtNumber   = 2
	jtString   = 3
	jtTemplate = 4
	jtPunct    = 5
	jtOperator = 6
)

func tokenize(src []byte) []jsToken {
	var tokens []jsToken
	i := 0
	line := 1

	for i < len(src) {
		ch := src[i]

		if ch == '\n' {
			line++
			i++
			continue
		}
		if ch == ' ' || ch == '\t' || ch == '\r' {
			i++
			continue
		}

		// Single-line comment.
		if ch == '/' && i+1 < len(src) && src[i+1] == '/' {
			for i < len(src) && src[i] != '\n' {
				i++
			}
			continue
		}

		// Multi-line comment.
		if ch == '/' && i+1 < len(src) && src[i+1] == '*' {
			i += 2
			for i+1 < len(src) {
				if src[i] == '\n' {
					line++
				}
				if src[i] == '*' && src[i+1] == '/' {
					i += 2
					break
				}
				i++
			}
			continue
		}

		// String literals.
		if ch == '"' || ch == '\'' {
			start := i
			quote := ch
			i++
			for i < len(src) && src[i] != quote {
				if src[i] == '\\' && i+1 < len(src) {
					i++
				}
				if src[i] == '\n' {
					line++
				}
				i++
			}
			if i < len(src) {
				i++
			}
			tokens = append(tokens, jsToken{typ: jtString, val: string(src[start:i]), line: line})
			continue
		}

		// Template literal.
		if ch == '`' {
			start := i
			i++
			depth := 0
			for i < len(src) {
				if src[i] == '\n' {
					line++
				}
				if src[i] == '\\' && i+1 < len(src) {
					i += 2
					continue
				}
				if src[i] == '$' && i+1 < len(src) && src[i+1] == '{' {
					depth++
					i += 2
					continue
				}
				if src[i] == '}' && depth > 0 {
					depth--
					i++
					continue
				}
				if src[i] == '`' && depth == 0 {
					i++
					break
				}
				i++
			}
			tokens = append(tokens, jsToken{typ: jtTemplate, val: string(src[start:i]), line: line})
			continue
		}

		// Numbers.
		if ch >= '0' && ch <= '9' {
			start := i
			i++
			for i < len(src) && isNumPart(src[i]) {
				i++
			}
			tokens = append(tokens, jsToken{typ: jtNumber, val: string(src[start:i]), line: line})
			continue
		}

		// Identifiers and keywords.
		if isIdentStart(ch) {
			start := i
			i++
			for i < len(src) && isIdentPart(src[i]) {
				i++
			}
			word := string(src[start:i])
			if isJSKeyword(word) {
				tokens = append(tokens, jsToken{typ: jtKeyword, val: word, line: line})
			} else {
				tokens = append(tokens, jsToken{typ: jtIdent, val: word, line: line})
			}
			continue
		}

		// Multi-char operators.
		if i+2 < len(src) {
			tri := string(src[i : i+3])
			if tri == "===" || tri == "!==" || tri == ">>>" || tri == "..." {
				tokens = append(tokens, jsToken{typ: jtOperator, val: tri, line: line})
				i += 3
				continue
			}
		}
		if i+1 < len(src) {
			bi := string(src[i : i+2])
			if bi == "==" || bi == "!=" || bi == "<=" || bi == ">=" || bi == "&&" || bi == "||" ||
				bi == "++" || bi == "--" || bi == "+=" || bi == "-=" || bi == "*=" || bi == "/=" ||
				bi == "=>" || bi == "?." || bi == "??" || bi == "**" || bi == ">>" || bi == "<<" {
				tokens = append(tokens, jsToken{typ: jtOperator, val: bi, line: line})
				i += 2
				continue
			}
		}

		// Single-char punctuation.
		tokens = append(tokens, jsToken{typ: jtPunct, val: string(ch), line: line})
		i++
	}
	return tokens
}

// --- Function finder ---

type funcSpan struct {
	name       string
	bodyTokens []jsToken
	startLine  int
	endLine    int
}

func findFunctions(tokens []jsToken, src []byte) []funcSpan {
	var funcs []funcSpan
	totalLines := bytes.Count(src, []byte("\n")) + 1

	i := 0
	for i < len(tokens) {
		name, bodyStart, ok := matchFunction(tokens, i)
		if !ok {
			i++
			continue
		}
		startLine := tokens[i].line

		// bodyStart points to the opening {.
		braceEnd := matchBraces(tokens, bodyStart)
		if braceEnd < 0 {
			i++
			continue
		}

		endLine := totalLines
		if braceEnd < len(tokens) {
			endLine = tokens[braceEnd].line
		}

		body := tokens[bodyStart : braceEnd+1]
		if len(body) > 2 { // more than just { }
			funcs = append(funcs, funcSpan{
				name:       name,
				bodyTokens: body,
				startLine:  startLine,
				endLine:    endLine,
			})
		}

		i = braceEnd + 1
	}
	return funcs
}

// matchFunction tries to match a function-defining pattern at position i.
// Returns the function name, the index of the opening { token, and whether it matched.
func matchFunction(tokens []jsToken, i int) (string, int, bool) {
	t := tokens[i]

	// Skip "async" prefix.
	off := 0
	if t.typ == jtKeyword && t.val == "async" && i+1 < len(tokens) {
		off = 1
		t = tokens[i+1]
	}

	// Pattern: function [*] [name] (
	if t.typ == jtKeyword && t.val == "function" {
		j := i + off + 1
		if j < len(tokens) && tokens[j].val == "*" {
			j++
		}
		name := "<anonymous>"
		if j < len(tokens) && tokens[j].typ == jtIdent {
			name = tokens[j].val
			j++
		}
		// Find opening {.
		for j < len(tokens) && tokens[j].val != "{" {
			j++
		}
		if j < len(tokens) {
			return name, j, true
		}
		return "", 0, false
	}

	// Pattern: ident ( ... ) { — method shorthand
	if t.typ == jtIdent && i+off+1 < len(tokens) && tokens[i+off+1].val == "(" {
		pClose := findCloseParen(tokens, i+off+1)
		if pClose > 0 && pClose+1 < len(tokens) && tokens[pClose+1].val == "{" {
			return t.val, pClose + 1, true
		}
	}

	// Pattern: [const|let|var] ident = [async] (...) => {
	// Pattern: ident = (...) => {
	// Pattern: ident: (...) => {
	// Pattern: ident: function(
	if t.typ == jtKeyword && (t.val == "const" || t.val == "let" || t.val == "var") {
		if i+off+1 < len(tokens) && tokens[i+off+1].typ == jtIdent {
			name := tokens[i+off+1].val
			// Scan forward for => or function keyword.
			for j := i + off + 2; j < len(tokens) && j < i+off+25; j++ {
				if tokens[j].val == "=>" {
					// Find {.
					for k := j + 1; k < len(tokens) && k < j+5; k++ {
						if tokens[k].val == "{" {
							return name, k, true
						}
					}
					break
				}
				if tokens[j].typ == jtKeyword && tokens[j].val == "function" {
					for k := j + 1; k < len(tokens); k++ {
						if tokens[k].val == "{" {
							return name, k, true
						}
					}
					break
				}
				if tokens[j].val == ";" || tokens[j].val == "}" {
					break
				}
			}
		}
	}

	return "", 0, false
}

func matchBraces(tokens []jsToken, start int) int {
	if start >= len(tokens) || tokens[start].val != "{" {
		return -1
	}
	depth := 1
	for j := start + 1; j < len(tokens); j++ {
		if tokens[j].val == "{" {
			depth++
		}
		if tokens[j].val == "}" {
			depth--
			if depth == 0 {
				return j
			}
		}
	}
	return -1
}

func findCloseParen(tokens []jsToken, start int) int {
	if start >= len(tokens) || tokens[start].val != "(" {
		return -1
	}
	depth := 1
	for j := start + 1; j < len(tokens); j++ {
		if tokens[j].val == "(" {
			depth++
		}
		if tokens[j].val == ")" {
			depth--
			if depth == 0 {
				return j
			}
		}
	}
	return -1
}

// --- Normalizer ---

func normalizeTokens(tokens []jsToken, level model.NormalizationLevel) []model.NormToken {
	var result []model.NormToken
	tracker := &identTracker{seen: make(map[string]string)}

	for _, t := range tokens {
		switch t.typ {
		case jtString, jtTemplate:
			if level >= model.NormLight {
				result = append(result, model.NormToken{Kind: token.STRING, Norm: "$STR", OrigLit: t.val})
			} else {
				result = append(result, model.NormToken{Kind: token.STRING, Norm: t.val, OrigLit: t.val})
			}
		case jtNumber:
			if level >= model.NormLight {
				result = append(result, model.NormToken{Kind: token.INT, Norm: "$NUM", OrigLit: t.val})
			} else {
				result = append(result, model.NormToken{Kind: token.INT, Norm: t.val, OrigLit: t.val})
			}
		case jtKeyword:
			result = append(result, model.NormToken{Kind: token.IDENT, Norm: t.val, OrigLit: t.val})
		case jtIdent:
			if level >= model.NormStrong && !isWellKnown(t.val) {
				result = append(result, model.NormToken{Kind: token.IDENT, Norm: tracker.get(t.val), OrigLit: t.val})
			} else {
				result = append(result, model.NormToken{Kind: token.IDENT, Norm: t.val, OrigLit: t.val})
			}
		case jtPunct, jtOperator:
			result = append(result, model.NormToken{Kind: punctToKind(t.val), Norm: t.val, OrigLit: t.val})
		}
	}
	return result
}

// --- Helpers ---

func splitStatements(tokens []model.NormToken) [][]model.NormToken {
	var stmts [][]model.NormToken
	var cur []model.NormToken
	for _, t := range tokens {
		cur = append(cur, t)
		if t.Norm == ";" || t.Norm == "{" || t.Norm == "}" {
			if len(cur) > 1 {
				stmts = append(stmts, cur)
			}
			cur = nil
		}
	}
	if len(cur) > 0 {
		stmts = append(stmts, cur)
	}
	return stmts
}

func estimateStatements(tokens []model.NormToken) int {
	count := 0
	for _, t := range tokens {
		if t.Norm == ";" || t.Norm == "}" {
			count++
		}
	}
	if count == 0 && len(tokens) > 0 {
		count = len(tokens) / 5
	}
	return count
}

func makeUnit(tokens []model.NormToken, region model.SourceRegion, kind model.UnitKind, level model.NormalizationLevel, stmtCount int) model.NormalizedUnit {
	h := sha256.New()
	for _, t := range tokens {
		_ = binary.Write(h, binary.BigEndian, int32(t.Kind))
		h.Write([]byte(t.Norm))
		h.Write([]byte{0})
	}
	var tokenHash [32]byte
	copy(tokenHash[:], h.Sum(nil))
	id := sha256.Sum256(append(tokenHash[:], []byte(region.File)...))
	return model.NormalizedUnit{
		ID:         id,
		Source:     region,
		Kind:       kind,
		NormTokens: tokens,
		NormLevel:  level,
		TokenHash:  tokenHash,
		ASTHash:    tokenHash,
		StmtCount:  stmtCount,
		NodeCount:  len(tokens),
	}
}

type identTracker struct {
	seen    map[string]string
	counter int
}

func (t *identTracker) get(name string) string {
	if n, ok := t.seen[name]; ok {
		return n
	}
	n := "$V" + strconv.Itoa(t.counter)
	t.counter++
	t.seen[name] = n
	return n
}

func isIdentStart(ch byte) bool {
	return ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z' || ch == '_' || ch == '$'
}
func isIdentPart(ch byte) bool { return isIdentStart(ch) || ch >= '0' && ch <= '9' }
func isNumPart(ch byte) bool {
	return ch >= '0' && ch <= '9' || ch == '.' || ch == 'x' || ch == 'X' || ch >= 'a' && ch <= 'f' || ch >= 'A' && ch <= 'F' || ch == 'n' || ch == '_' || ch == 'e' || ch == 'E'
}

func isJSKeyword(word string) bool {
	switch word {
	case "async", "await", "break", "case", "catch", "class", "const", "continue",
		"debugger", "default", "delete", "do", "else", "export", "extends",
		"false", "finally", "for", "function", "if", "import", "in", "instanceof",
		"let", "new", "null", "of", "return", "static", "super", "switch",
		"this", "throw", "true", "try", "typeof", "undefined", "var", "void",
		"while", "with", "yield",
		"abstract", "as", "declare", "enum", "implements", "interface",
		"module", "namespace", "private", "protected", "public", "readonly",
		"type", "keyof", "infer", "is", "never", "unknown", "any":
		return true
	}
	return false
}

func isWellKnown(name string) bool {
	switch name {
	case "console", "document", "window", "global", "process",
		"require", "module", "exports", "Promise", "Array", "Object",
		"String", "Number", "Boolean", "Error", "Map", "Set",
		"JSON", "Math", "Date", "RegExp", "Symbol", "Buffer",
		"setTimeout", "setInterval", "clearTimeout", "clearInterval",
		"parseInt", "parseFloat", "isNaN", "isFinite",
		"undefined", "null", "NaN", "Infinity", "globalThis",
		"React", "Component", "useState", "useEffect", "useCallback",
		"useMemo", "useRef", "useContext", "useReducer", "Fragment",
		"PropTypes", "createElement":
		return true
	}
	return false
}

func punctToKind(val string) token.Token {
	switch val {
	case "(":
		return token.LPAREN
	case ")":
		return token.RPAREN
	case "{":
		return token.LBRACE
	case "}":
		return token.RBRACE
	case "[":
		return token.LBRACK
	case "]":
		return token.RBRACK
	case ";":
		return token.SEMICOLON
	case ",":
		return token.COMMA
	case ".":
		return token.PERIOD
	case ":":
		return token.COLON
	case "=":
		return token.ASSIGN
	case "+":
		return token.ADD
	case "-":
		return token.SUB
	case "*":
		return token.MUL
	case "/":
		return token.QUO
	case "<":
		return token.LSS
	case ">":
		return token.GTR
	case "!":
		return token.NOT
	default:
		return token.IDENT
	}
}
