package model

import "encoding/json"

// RefactorCategory classifies the type of refactoring suggested for a clone finding.
type RefactorCategory int

const (
	// RefactorExtractHelper suggests extracting the repeated code into a shared helper function.
	RefactorExtractHelper RefactorCategory = iota

	// RefactorGenericFunc suggests converting the helper into a generic function using type parameters.
	RefactorGenericFunc

	// RefactorTableDriven suggests replacing repeated similar code with a table-driven approach.
	RefactorTableDriven

	// RefactorSharedValidator suggests extracting shared validation logic into a common validator.
	RefactorSharedValidator

	// RefactorAdapterMapper suggests creating an adapter or mapper to consolidate similar transformations.
	RefactorAdapterMapper

	// RefactorInterfaceExtract suggests extracting a common interface and implementing it.
	RefactorInterfaceExtract

	// RefactorConfigDriven suggests making the repeated logic configuration-driven.
	RefactorConfigDriven
)

// String returns the canonical string representation of a RefactorCategory.
func (c RefactorCategory) String() string {
	switch c {
	case RefactorExtractHelper:
		return "extract_helper"
	case RefactorGenericFunc:
		return "generic_func"
	case RefactorTableDriven:
		return "table_driven"
	case RefactorSharedValidator:
		return "shared_validator"
	case RefactorAdapterMapper:
		return "adapter_mapper"
	case RefactorInterfaceExtract:
		return "interface_extract"
	case RefactorConfigDriven:
		return "config_driven"
	default:
		return "unknown"
	}
}

// MarshalJSON encodes RefactorCategory as its string name.
func (c RefactorCategory) MarshalJSON() ([]byte, error) { return json.Marshal(c.String()) }

// RefactorHint is an actionable refactoring suggestion attached to a clone finding.
// Hints are generated by heuristics that analyze the structure of the clone regions.
type RefactorHint struct {
	Category    RefactorCategory `json:"category"`
	Description string           `json:"description"`
	Confidence  float64          `json:"confidence"`
}
