package lang

import (
	"crypto/sha256"
	"encoding/binary"
	"strconv"
	"strings"

	"github.com/user/amimica/internal/model"
)

// MakeUnit creates a NormalizedUnit from a token sequence and region.
// Shared by all non-Go language implementations to avoid duplication.
func MakeUnit(tokens []model.NormToken, region model.SourceRegion, kind model.UnitKind, level model.NormalizationLevel, stmtCount int) model.NormalizedUnit {
	tokenHash := HashTokens(tokens)
	id := sha256.Sum256(append(tokenHash[:], []byte(region.File)...))
	return model.NormalizedUnit{
		ID:         id,
		Source:     region,
		Kind:       kind,
		NormTokens: tokens,
		NormLevel:  level,
		TokenHash:  tokenHash,
		ASTHash:    tokenHash,
		StmtCount:  stmtCount,
		NodeCount:  len(tokens),
	}
}

// HashTokens computes SHA-256 over a normalized token sequence.
func HashTokens(tokens []model.NormToken) [32]byte {
	h := sha256.New()
	for _, t := range tokens {
		_ = binary.Write(h, binary.BigEndian, int32(t.Kind))
		h.Write([]byte(t.Norm))
		h.Write([]byte{0})
	}
	var result [32]byte
	copy(result[:], h.Sum(nil))
	return result
}

// SplitByDelimiters splits a normalized token sequence into statement groups,
// breaking at any token whose Norm value is in the delimiters set.
func SplitByDelimiters(tokens []model.NormToken, delimiters []string) [][]model.NormToken {
	delimSet := make(map[string]bool, len(delimiters))
	for _, d := range delimiters {
		delimSet[d] = true
	}

	var stmts [][]model.NormToken
	var cur []model.NormToken
	for _, t := range tokens {
		cur = append(cur, t)
		if delimSet[t.Norm] {
			if len(cur) > 1 {
				stmts = append(stmts, cur)
			}
			cur = nil
		}
	}
	if len(cur) > 0 {
		stmts = append(stmts, cur)
	}
	return stmts
}

// IsGeneratedContent checks the first 2048 bytes of file content for common
// generated-code markers. Shared by JS/TS and Ruby language implementations.
func IsGeneratedContent(content []byte) bool {
	check := content
	if len(check) > 2048 {
		check = check[:2048]
	}
	s := string(check)
	return strings.Contains(s, "DO NOT EDIT") ||
		strings.Contains(s, "auto-generated") ||
		strings.Contains(s, "Auto-generated") ||
		strings.Contains(s, "Generated by") ||
		strings.Contains(s, "@generated")
}

// IdentTracker assigns positional placeholder names ($V0, $V1, ...) to
// identifiers during strong normalization. Shared by JS/TS and Ruby.
type IdentTracker struct {
	seen    map[string]string
	counter int
}

// NewIdentTracker creates a new tracker.
func NewIdentTracker() *IdentTracker {
	return &IdentTracker{seen: make(map[string]string)}
}

// Get returns the normalized placeholder for name, creating one if first seen.
func (t *IdentTracker) Get(name string) string {
	if n, ok := t.seen[name]; ok {
		return n
	}
	n := "$V" + strconv.Itoa(t.counter)
	t.counter++
	t.seen[name] = n
	return n
}
